// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lixepcqyasyxqiqfqhjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeGVwY3F5YXN5eHFpcWZxaGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODE1MTIsImV4cCI6MjA4NTM1NzUxMn0.PwB3cf0Rrasefz-tN7udAJEahpJgM6l9a3g_FYPsYFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});